// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using blogpessoal.Data;

#nullable disable

namespace blogpessoal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525163403_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.HasKey("Id");

                    b.ToTable("tb_temas", (string)null);
                });

            modelBuilder.Entity("blogpessoal.Model.Postagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TemaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("Varchar");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tb_postagens", (string)null);
                });

            modelBuilder.Entity("blogpessoal.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .HasColumnType("Varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("Varchar");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("Varchar");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("Varchar");

                    b.HasKey("Id");

                    b.ToTable("tb_usuarios", (string)null);
                });

            modelBuilder.Entity("blogpessoal.Model.Postagem", b =>
                {
                    b.HasOne("Tema", "Tema")
                        .WithMany("Postagem")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("blogpessoal.Model.User", "Usuario")
                        .WithMany("Postagem")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tema");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tema", b =>
                {
                    b.Navigation("Postagem");
                });

            modelBuilder.Entity("blogpessoal.Model.User", b =>
                {
                    b.Navigation("Postagem");
                });
#pragma warning restore 612, 618
        }
    }
}
